version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ticketing-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jofksnx4ss9z"
s3_prefix = "ticketing-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
