AWSTemplateFormatVersion: 2010-09-09
Description: ticketing-app
Transform:
- AWS::Serverless-2016-10-31
Resources:
  counterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/counter.run
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 900
      Description: Counts the tickets
      Policies:
      - CloudWatchPutMetricPolicy: {}
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TicketingTable
      Environment:
        Variables:
          SAMPLE_TABLE:
            Ref: TicketingTable
  getAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-all-items.getAllItemsHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get all items from
        a DynamoDB table.
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TicketingTable
      Environment:
        Variables:
          SAMPLE_TABLE:
            Ref: TicketingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
      # CodeUri: getAllItemsFunction
  getByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-id.getByIdHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A simple example includes a HTTP get method to get one item by
        id from a DynamoDB table.
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TicketingTable
      Environment:
        Variables:
          SAMPLE_TABLE:
            Ref: TicketingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
      # CodeUri: getByIdFunction
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler 
      AutoPublishAlias: prod
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Tracing: Active
      Description: A simple example includes a HTTP post method to add one item to
        a DynamoDB table.
      Layers:
        - arn:aws:lambda:us-east-1:994092007821:layer:nodejs-concurrency-extension:10
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TicketingTable
      - CloudWatchPutMetricPolicy: {}
      Environment:
        Variables:
          SAMPLE_TABLE:
            Ref: TicketingTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
      # CodeUri: putItemFunction
  TicketingTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE      
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: deviceID
          AttributeType: S
        - AttributeName: created
          AttributeType: N
      GlobalSecondaryIndexes:
        - IndexName: InvertedKeys
          KeySchema:
            - AttributeName: deviceID
              KeyType: HASH
            - AttributeName: created
              KeyType: RANGE
          Projection:
            ProjectionType: ALL        
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
